### ISSUE TITLE
[Feature request] 64-bit integer seed

### ISSUE THREAD

**Issue by cs127** [2000Slash/Seedslider#1]
Minecraft seeds are 64-bit, but the current slider only allows 32-bit values.

A 64-bit integer slider would be even more ridiculous, therefore much better.

I don't know how easy this is to implement, given that the integer range for `SimpleOption` uses `int`s instead of `long`s, but if it is possible, I would love to see it get added.

**Comment by 2000Slash** [comment]
I implemented it, but for some reason when installing the mod and running it the normal way, the LongSliderCallbacks cannot access SliderCallbacks and Minecraft crashes sooo...

**Comment by 2000Slash** [comment]
Nvm i fixed it now lol

**Comment by cs127** [comment]
amazing
